services:
  - type: web
    name: eticaret-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://eticaret-vitrin.onrender.com
